In [1]:
import NNSA

# List of available models:

In [2]:
NNSA.available_models()

Available models: BaSTIModel, PARSECModel, MISTModel, SYCLISTModel, DartmouthModel, YaPSIModel


# Load BaSTI model:
### By default, the age models use sklearn to run the neural networks. If you do not have it installed, or don't want to use it, you can pass the argument 'use_sklearn=False' to switch to a numpy version. Be aware though, it becomes significantly slower once you run the models on more than ~100 stars.

In [3]:
#age_model = NNSA.BaSTIModel(use_sklearn=False)
age_model = NNSA.BaSTIModel()

# Estimate the age of a single star using [M/H],MG,BPRP:

In [4]:
age_model.ages_prediction(MH=0.0,MG=4.0,BPRP=1.0)

array([[13.70947757]])

# Estimate the age of a single star using [M/H],MG,BPRP,GBP & GRP:

In [3]:
age_model.ages_prediction(MH=0.0,MG=2.0,BPRP=1.0,GBP=2.0,GRP=1.0)

array([[1.38048182]])

# Estimate the age of multiple stars:

In [18]:
age_model.ages_prediction(MH=[0.0,-1.0],MG=[2.0,3.0],BPRP=[1.0,0.5])

array([[1.72752871],
       [5.67700616]])

# Estimate the age of a single star with n=10 Monte Carlo realisations using errors:

In [23]:
age_model.ages_prediction(MH=0.0,MG=2.0,BPRP=1.0,eMH=0.1,eMG=0.1,eBPRP=0.1,n=10)

array([[2.03544739, 1.59207102, 2.03022214, 1.72963817, 1.74013068,
        2.00467239, 1.67545067, 1.97295733, 2.88586463, 1.85107073]])

### Once the ages have been predicted for each star n times, you can call statistical methods model.mean_ages(), model.median_ages(), model.mode_ages() and model.std_ages()

In [24]:
print(age_model.mean_ages())
print(age_model.median_ages())
print(age_model.mode_ages())
print(age_model.std_ages())

[1.95175252]
[1.91201403]
[2.05]
[0.34625811]
